/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Probe {
    pub _address: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Probe"][::std::mem::size_of::<Probe>() - 4usize];
    ["Alignment of Probe"][::std::mem::align_of::<Probe>() - 4usize];
};
