[package]
name = "rezie-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
rezie-engine.workspace = true
rezie-api.workspace = true
eframe.workspace = true
anyhow.workspace = true
tracing.workspace = true
wgpu.workspace = true

[lints]
workspace = true
